export const socials = [
    {
        name: 'whatsapp',
        url: '/images/socials/whatsapp.svg',
        link: 'https://wa.me/84349932192',
    },
    {
        name: 'github',
        url: '/images/socials/github.svg',
        link: 'https://github.com/nmchi',
    },
    {
        name: 'facebook',
        url: '/images/socials/facebook.svg',
        link: 'https://www.facebook.com/baron0124/',
    },
];

export const projectsData = [
    {
        id: 1,
        title: "Beautyl",
        description: "BEAUTY'L where we provide you with bespoke beauty services, including premium Eyelash Extensions, Eyebrows Lamination, Semi-permanent make-up and Waxing. With outstanding quality using only the safest and latest products and techniques",
        image: "/images/project/wordpress/beautyl.png",
        tag: ["All", "WordPress"],
        gitUrl: "/",
        previewUrl: "https://www.beautyl.com.au/",
    },
    {
        id: 2,
        title: "Auvin",
        description: "Auvin is a boutique wine merchant that was founded by a group of passionate wine lovers who wanted to share their knowledge and love of wine with others.",
        image: "/images/project/wordpress/auvin.png",
        tag: ["All", "WordPress"],
        gitUrl: "/",
        previewUrl: "https://auvin.com.au/",
    },
    {
        id: 3,
        title: "Office Works",
        description: "OfficeworksR always listens, shares and supports customers to overcome all obstacles in project implementation to complete the project in the best way. OfficeworksR ‘s greatest pride is when customers use OfficeworksR’s solutions effectively, and are respected and loved by customers after each project.",
        image: "/images/project/wordpress/office.png",
        tag: ["All", "WordPress"],
        gitUrl: "/",
        previewUrl: "https://officeworksr.com/",
    },
    {
        id: 4,
        title: "Vano",
        description: "VANO is cooperating and deploying on all 3 networks MobiFone, Viettel, VinaPhone with nearly 20 services, many of which are of high quality, attracting a large number of customers.",
        image: "/images/project/wordpress/vano.png",
        tag: ["All", "WordPress"],
        gitUrl: "/",
        previewUrl: "http://vano.vn/",
    },
    {
        id: 5,
        title: "Gas",
        description: "Gas info",
        image: "/images/project/wordpress/gas.png",
        tag: ["All", "WordPress"],
        gitUrl: "/",
        previewUrl: "https://gascongnghiep.vn/",
    },
    {
        id: 6,
        title: "GreenHouse",
        description: "The Green House Vietnam brand was chosen with the meaning of 'Green House', a house with vitality, always rising, following nature, it is also an ecological house, always close and in harmony with nature to brings a sense of peace to people.",
        image: "/images/project/wordpress/house.png",
        tag: ["All", "WordPress"],
        gitUrl: "/",
        previewUrl: "https://greenhouse.com.vn/",
    },
    {
        id: 7,
        title: "Finantaged",
        description: "Finantaged",
        image: "/images/project/next_react_js/finan.png",
        tag: ["All", "NextJS"],
        gitUrl: "/",
        previewUrl: "https://finantaged.com/",
    },
    {
        id: 8,
        title: "VasGame",
        description: "Vas game",
        image: "/images/project/next_react_js/topgame.png",
        tag: ["All", "NextJS"],
        gitUrl: "/",
        previewUrl: "https://mcn-game-app.netlify.app/",
    },
    {
        id: 9,
        title: "Modern",
        description: "Hoo bank",
        image: "/images/project/next_react_js/bank.png",
        tag: ["All", "NextJS"],
        gitUrl: "/",
        previewUrl: "https://bnbank-modern.vercel.app/",
    },
    {
        id: 10,
        title: "Ware",
        description: "Ware design from Figma, use ReactJS, Tailwind CSS, ViteJS",
        image: "/images/project/next_react_js/ware.png",
        tag: ["All", "NextJS"],
        gitUrl: "/",
        previewUrl: "https://bnware.vercel.app/",
    },
];